In [18]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from function import lineal, sigmoide, derivate_sigmoide, derivate_lineal,Backpropagation, derivate_error
import os
import math

In [19]:
#Inicializamos los pesos de la Capa 1
w = np.random.random(500)
w11 = w[:100]
w12 = w[100:200]
w13 = w[200:300]
w14 = w[300:400]
w15 = w[400:500]
W1=[w11,w12,w13,w14,w15]

#Inicializamos los pesos de la Capa 2
w = np.random.random(25)
w21 = w[:5]
w22 = w[5:10]
w23 = w[10:15]
w24 = w[15:20]
w25 = w[20:25]
W2 = [w21,w22,w23,w24,w25] 

#Incializamos los pesos de la Capa 3
w = np.random.random(15)
w31 = w[:5]
w32 = w[5:10]
w33 = w[10:15]
W3 = [w31,w32,w33]

#Bias
b = random.random()

#Factor de aprendizaje
alfa = random.random()

#Codificacion de clases
#b = 100
#d = 010
#f = 001

In [20]:
data = (pd.read_csv(os.path.join(os.path.abspath(''),"data","distorsionadas",'100','letras.csv'),sep=';',header=None)).to_numpy()
#Convertimos el dataframe en array numpy
data_train = data[:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8)+1:int(len(data)*0.8)+int(len(data)*0.15)]
data_validation = data[int(len(data)*0.8)+int(len(data)*0.15)+1:99]

In [21]:
#Dividiendo data train en una tupla (entrada,clase)
letras_train = []
for letra in data_train:
    x_test = letra[:100]
    y_test = letra[100:]
    letras_train.append((x_test, y_test))


In [22]:

for i in range(1):

    #Primer capa
    ys1 =[]
    for j in range(len(W1)):
        #Suma ponderada
        Z = np.dot(letras_train[i][0],W1[j])
        #Funcion de activacion
        ys1.append(lineal(Z+b))
    #print("Primer capa: ", ys1)

    #Segunda capa
    ys2 = []
    for j in range(len(W2)):
        #Suma ponderada
        Z = np.dot(ys1,W2[j])
        #Funcion de activacion
        ys2.append(lineal(Z+b))
    #print("2da capa: ", ys2)
    #Capa de salida
    ys3 = []
    for j in range(len(W3)):
        #Suma ponderada
        Z = np.dot(ys2,W3[j])
        #Funcion de activacion
        ys3.append(sigmoide(Z+b))
    #print("Capa salida: ", ys3)

    #!!-------Backpropagation-----!!
    ys1 = np.array(ys1)
    ys2 = np.array(ys2)
    ys3 = np.array(ys3)
    activaciones = [ys1,ys2,ys3]
    W = [W2,W3]
    ye = letras_train[i][1]
    Backpropagation(ye,activaciones,W)
    #!!----- Gradient descent------!!
    
    

In [9]:
deltaOut = derivate_error(ye,activaciones[len(activaciones)-1])*derivate_sigmoide(activaciones[len(activaciones)-1])
w = np.transpose(W3)
np.dot(w,deltaOut)

array([0.03396665, 0.03867365, 0.02653851, 0.02064131, 0.02924879])

In [14]:
w = np.transpose(W3)
delta3 =[0.8,0.3,0.2]
delta3 =np.array(delta3)
for i in range (len(w)):
    print(np.sum(w[i]*delta3))


0.9087945525466244
0.7643735257526132
0.48824712984434493
0.6249536468852334
0.5369684931280057


In [26]:
W =[W1,W2,W3]
delta3 = [2,2,2]
delta3 =np.array(delta3)

for capa in reversed(W):
    w = np.transpose(capa)
    for i in range(len(w)):
        print(w[i]*delta3)

[0.95861161 0.28189526 0.64351681]
[1.17779224 0.80951571 0.97059702]
[0.21724085 0.7791144  0.0468894 ]
[1.40225562 1.61449468 1.63440745]
[1.02568525 1.84944324 0.84591095]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 