In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import os
import math
import functionsMaths as f

In [2]:
#Inicializamos los pesos de la Capa 1
w = np.random.random(500)
w11 = w[:100]
w12 = w[100:200]
w13 = w[200:300]
w14 = w[300:400]
w15 = w[400:500]
W1=[w11,w12,w13,w14,w15]

#Inicializamos los pesos de la Capa 2
w = np.random.random(25)
w21 = w[:5]
w22 = w[5:10]
w23 = w[10:15]
w24 = w[15:20]
w25 = w[20:25]
W2 = [w21,w22,w23,w24,w25] 

#Incializamos los pesos de la Capa 3
w = np.random.random(15)
w31 = w[:5]
w32 = w[5:10]
w33 = w[10:15]
W3 = [w31,w32,w33]

#Bias
b = np.random.random(13)

b1= b[:5]
b2 = b[5:10]
b3 = b [10:]


# pesos
w1 = np.array(W1)
w2 = np.array(W2)
w3 = np.array(W3)





In [3]:
data = (pd.read_csv(os.path.join(os.path.abspath(''),"data","distorsionadas",'100','letras.csv'),sep=';',header=None)).to_numpy()
#Convertimos el dataframe en array numpy
data_train = data[:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8)+1:int(len(data)*0.8)+int(len(data)*0.15)]
data_validation = data[int(len(data)*0.8)+int(len(data)*0.15)+1:99]
len(data_test)
len(data_train)



80

In [4]:
def divX_Y(letras):
    for letra in letras:
        x_train = letra[:100]
        y_train = letra[100:]
    return x_train,y_train

In [5]:
#Dividiendo data train en una tupla (entrada,clase)
letras_train = []
data_test_predict = []
for letra in data_train:
    x_train = letra[:100]
    y_train = letra[100:]
    letras_train.append((x_train, y_train))

for letra in data_test:
    x_train = letra[:100]
    y_train = letra[100:]
    data_test_predict.append((x_train, y_train))

len(data_test_predict)

14

In [6]:
er = [0,0,0]
    
er = np.array([0,0,0])
Ye = np.array([1,0,0])
ys3 = np.array([0.69,0.73,0.23])

er = np.sum([er, (Ye-ys3)**2], axis=0)

print(er)

Ye = np.array([1,0,0])
ys3 = np.array([0.69,0.73,0.23])

er = np.sum([er, (Ye-ys3)**2], axis=0)

print(er)

Ye = np.array([1,0,0])
ys3 = np.array([0.69,0.73,0.23])

er = np.sum([er, (Ye-ys3)**2], axis=0)

print(er/3)

[0.0961 0.5329 0.0529]
[0.1922 1.0658 0.1058]
[0.0961 0.5329 0.0529]


In [8]:
err = []
for e in range(100):
    
    er = np.array([0,0,0])
    np.random.shuffle(letras_train)
    for i in range(len(letras_train)):
                # feedforward
                #Primer capa
                ys1 =[]
                z1 = []
                deltas = []
                zs = []
                activaciones = [letras_train[i][0]]
                for j in range(len(w1)):
                    #Suma ponderada
                    Z1 = np.dot(letras_train[i][0],w1[j])
                    #Funcion de activacion
                    ys1.append(f.lineal(Z1+b1[j]))
                    z1.append(Z1)
                
                z1 = np.array(z1)
                ys1 = np.array(ys1)

                activaciones.append(ys1)
                zs.append(z1)
                #Segunda capa
                ys2 = []
                z2 = []
                for j in range(len(w2)):
                    #Suma ponderada
                    Z2 = np.dot(ys1,w2[j])
                    #Funcion de activacion
                    ys2.append(f.lineal(Z2+b2[j]))
                    z2.append(Z2)
                
                z2 = np.array(z2)
                ys2 = np.array(ys2)
                
                activaciones.append(ys2)
                zs.append(z2)
                #Capa de salida
                ys3 = []
                z3 = []
                for j in range(len(w3)):
                    #Suma ponderada
                    Z3 = np.dot(ys2,w3[j])
                    #Funcion de activacion
                    ys3.append(f.sigmoide(Z3+b3[j]))
                    z3.append(Z3)
                #print("Capa salida: ", ys3)
                #!!-----Calculo del error-----!!!

                ys3 = np.array(ys3)
                z3 = np.array(z3)

                activaciones.append(ys3)
                zs.append(z3)

                Ye = np.array(letras_train[i][1])
                #----------------------------------------------------#
                
                er = np.sum([er, (Ye-ys3)**2], axis=0)
                delta = f.cost_derivate(activaciones[3], Ye)*f.sigmoide_derivate(z3)
                delta = np.array(delta)
                b3 -= delta*0.3 

                deltas.append(delta)
                ##print(ys3, letras_train[i][1],delta)
                #CAPA OCULTA N° 2
                delta2 = np.dot(np.transpose(w3),deltas[0])*f.lineal_derivate()
                b2 -= delta2*0.3

                deltas.append(delta2)

                #CAPA OCULTA N° 1
                delta1 = np.dot(np.transpose(w2),deltas[1])*f.lineal_derivate()
                b1 -= delta1*0.3

                deltas.append(delta1)

                #Backforward
                for j in range(len(w3)):
                    for k in range(len(w2)):
                        w3[j][k] -= activaciones[2][k]*deltas[0][j]*0.3
                
                for j in range(len(w2)):
                    for k in range(len(w1)):
                        w2[j][k] -= activaciones[1][k]*deltas[1][j]*0.3

                for j in range(len(w1)):
                    for k in range(100):
                        w1[j][k] -= activaciones[0][k]*deltas[2][j]*0.3
    
    
    er = er/(2*len(letras_train))
    err.append(er)
            

In [9]:
for e in err:
    print(np.mean(e))

0.056612170092169116
0.05656426908782373
0.05666978917460794
0.056646564152840334
0.05667356921742284
0.05678318911114041
0.056645389025908495
0.05662462343176447
0.05669503100329328
0.056594794732969994
0.05672003104730997
0.05662195130004327
0.05659781574702482
0.056630133002016046
0.05666055547748453
0.05668273881244371
0.056642610278155175
0.05663731084279414
0.05662723027049274
0.05671218190565705
0.056643872772247215
0.05666143731169856
0.05667184927069388
0.056612475363353176
0.056589801353061804
0.056562186293373916
0.056597061131853255
0.056646404141943406
0.05656635005129623
0.05663046477580417
0.05663739100098572
0.05666938602857258
0.05666645218760858
0.056640153741830845
0.05659512312067331
0.056617885165499045
0.0565093041522618
0.05670091056644213
0.05675058483718529
0.05667953081511621
0.056626190987939445
0.05668629940904829
0.05664508089451861
0.05658738585572289
0.056755384508347946
0.05661464985799377
0.05669211409375249
0.05667246693640163
0.05668280259785737
0.056

In [10]:
def backforward(W,activations, deltas,num_layers, lr, m):
    i = 0
    for w in W:
        x,y = w.shape
        for j in range(x):
            for k in range(k):
                w[j][k] -= activations[i][k]*deltas[i][j]*lr*m
                




In [11]:

## PREDICT 
letra = ["b","d","f"]
porcentaje = 0
for i in range(len(data_test_predict)):
    ys1 =[]
    z1 = []
    for j in range(len(w1)):
                #Suma ponderada
        Z1 = np.dot(data_test_predict[i][0],w1[j])
                #Funcion de activacion
        ys1.append(f.lineal(Z1+b1[j]))
        z1.append(Z1)
                
    z1 = np.array(z1)
    ys1 = np.array(ys1)

    #print("Primer capa: ", ys1)
    #Segunda capa
    ys2 = []
    z2 = []
    for j in range(len(w2)):
        #Suma ponderada
        Z2 = np.dot(ys1,w2[j])
        #Funcion de activacion
        ys2.append(f.lineal(Z2+b2[j]))
        z2.append(Z2)
                
    z2 = np.array(z2)
    ys2 = np.array(ys2)

    #print("2da capa: ", ys2)
    #Capa de salida
    ys3 = []
    z3 = []
    for j in range(len(w3)):
        #Suma ponderada
        Z3 = np.dot(ys2,w3[j])
        #Funcion de activacion
        ys3.append(f.sigmoide(Z3+b3[j]))
        z3.append(Z3)
                #print("Capa salida: ", ys3)
                #!!-----Calculo del error-----!!!

    ys3 = np.array(ys3)
    z3 = np.array(z3)

    if(np.argmax(ys3) == np.argmax(data_test_predict[i][1])):
        porcentaje += 1
    print("Prediccion: {} letra: {} ---- valor real: {}, letra: {}".format( np.argmax(ys3)+1,letra[ np.argmax(ys3)],np.argmax(data_test_predict[i][1])+1,letra[np.argmax(data_test_predict[i][1])] ))
print("Porcentaje predicho: {}%".format((porcentaje/len(data_test_predict))*100))

Prediccion: 3 letra: f ---- valor real: 3, letra: f
Prediccion: 2 letra: d ---- valor real: 2, letra: d
Prediccion: 2 letra: d ---- valor real: 1, letra: b
Prediccion: 2 letra: d ---- valor real: 2, letra: d
Prediccion: 2 letra: d ---- valor real: 1, letra: b
Prediccion: 2 letra: d ---- valor real: 1, letra: b
Prediccion: 3 letra: f ---- valor real: 3, letra: f
Prediccion: 3 letra: f ---- valor real: 3, letra: f
Prediccion: 2 letra: d ---- valor real: 1, letra: b
Prediccion: 3 letra: f ---- valor real: 3, letra: f
Prediccion: 2 letra: d ---- valor real: 1, letra: b
Prediccion: 3 letra: f ---- valor real: 2, letra: d
Prediccion: 2 letra: d ---- valor real: 2, letra: d
Prediccion: 2 letra: d ---- valor real: 2, letra: d
Porcentaje predicho: 57.14285714285714%
