In [3]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from function import lineal, sigmoide, derivate_sigmoide, error, derivate_lineal
import os
import math

In [2]:
#Inicializamos los pesos de la Capa 1
w = np.random.random(500)
w11 = w[:100]
w12 = w[100:200]
w13 = w[200:300]
w14 = w[300:400]
w15 = w[400:500]
W1=[w11,w12,w13,w14,w15]

#Inicializamos los pesos de la Capa 2
w = np.random.random(25)
w21 = w[:5]
w22 = w[5:10]
w23 = w[10:15]
w24 = w[15:20]
w25 = w[20:25]
W2 = [w21,w22,w23,w24,w25] 

#Incializamos los pesos de la Capa 3
w = np.random.random(15)
w31 = w[:5]
w32 = w[5:10]
w33 = w[10:15]
W3 = [w31,w32,w33]

#Bias
b = random.random()

#Factor de aprendizaje
alfa = random.random()

#Codificacion de clases
#b = 100
#d = 010
#f = 001

In [3]:
data = (pd.read_csv(os.path.join(os.path.abspath(''),"data","distorsionadas",'100','letras.csv'),sep=';',header=None)).to_numpy()
#Convertimos el dataframe en array numpy
data_train = data[:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8)+1:int(len(data)*0.8)+int(len(data)*0.15)]
data_validation = data[int(len(data)*0.8)+int(len(data)*0.15)+1:99]

In [4]:
#Dividiendo data train en una tupla (entrada,clase)
letras_train = []
for letra in data_train:
    x_test = letra[:100]
    y_test = letra[100:]
    letras_train.append((x_test, y_test))


In [6]:
print("W3 sin actualizar:\n",W3)
print("W2 sin actualizar:\n",W2)
#print("W1 sin actualizar:\n",W1)

for i in range(80):

    #Primer capa
    ys1 =[]
    for j in range(len(W1)):
        #Suma ponderada
        Z = np.dot(letras_train[i][0],W1[j])
        #Funcion de activacion
        ys1.append(lineal(Z+b))
    #print("Primer capa: ", ys1)

    #Segunda capa
    ys2 = []
    for j in range(len(W2)):
        #Suma ponderada
        Z = np.dot(ys1,W2[j])
        #Funcion de activacion
        ys2.append(sigmoide(Z+b))
    #print("2da capa: ", ys2)
    #Capa de salida
    ys3 = []
    for j in range(len(W3)):
        #Suma ponderada
        Z = np.dot(ys2,W3[j])
        #Funcion de activacion
        ys3.append(sigmoide(Z+b))
    #print("Capa salida: ", ys3)
    #!!-------Backpropagation-----!!
    ys1 = np.array(ys1)
    ys2 = np.array(ys2)
    ys3 = np.array(ys3)
    #Delta en capa 3
    delta3 = []
    for j in range(len(ys3)):
        # error[j]*f'(a[j])
        derivate_cost =-error(letras_train[i][1][j], ys3[j])
        delta3.append(derivate_cost*derivate_sigmoide(ys3[j]))
    
    #Delta en capa 2
    delta2 = []
    W = np.transpose(W3)
    for j in range(len(W)):
        delta2.append(np.dot(W[j],delta3)*ys2[j])
   
    #Delta en capa oculta 1
    delta1 = []
    W = np.transpose(W2)
    for j in range(len(W)):
        delta1.append(np.dot(W[j],delta2)*ys1[j])
   
    
    #!!---- Gradient descent -------!!
    delta3 = np.array(delta3)
    delta2 = np.array(delta2)
    delta1 = np.array(delta1)
    W3 = np.transpose(W3)
    W2 = np.transpose(W2)
    W1 = np.transpose(W1)
    #Capa 3
    new_weight = []
    for j in range(len(W3)):
        new_weight.append(W3[j]+alfa*delta3*ys3)
    W3 = np.array(new_weight)
    
    #Capa 2
    new_weight = []
    for j in range(len(W2)):
        new_weight.append(W2[j]+alfa*delta2*ys2)
    W2 = np.array(new_weight)

    #Capa 1
    new_weight = []
    for j in range(len(W1)):
        new_weight.append(W1[j]+alfa*delta1*ys1)
    W1 = np.array(new_weight)
    #pesos actualizados
    W3 = np.transpose(W3)
    W2 = np.transpose(W2)
    W1 = np.transpose(W1)

print("W3 actualizado:\n",W3)
print("W2 actualizado:\n",W2)
#print("W1 actualizado:\n",W1)

W3 sin actualizar:
 [[0.02499537 0.56895597 0.9323185  0.64166249 0.62270712]
 [0.48015696 0.01276354 0.33316232 0.68266208 0.73841656]
 [0.89572861 0.26063442 0.23776221 0.11723033 0.3209823 ]]
W2 sin actualizar:
 [[0.88765322 0.38568663 1.03329534 0.6391347  0.91002566]
 [0.59830298 0.09841071 1.02502697 0.27946655 0.53438245]
 [0.280924   0.31446202 0.12444915 0.97698835 1.02212681]
 [0.71421705 0.67357069 0.08781404 0.3543272  0.05285765]
 [0.58235775 0.55478154 0.19329764 0.85382843 0.25026197]]
W3 actualizado:
 [[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
W2 actualizado:
 [[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]


C:\Users\aleoc\AppData\Local\Temp\ipykernel_14048\583300128.py:78: RuntimeWarning: overflow encountered in multiply
  new_weight.append(W1[j]+alfa*delta1*ys1)


In [6]:
A = np.array([1,2,3])
B = np.array([4,4,2])
result = 0
for i in range(100):
    result = result + A*B
result

array([400, 800, 600])

In [14]:
y =[1,2,3,4]
y = np.array(y)
for i in reversed(y):
    print(i)

4
3
2
1
