In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from function import lineal, sigmoide, derivate_sigmoide, derivate_lineal,Backpropagation, derivate_error,Gradientdescent
import os
import math

In [2]:
#Inicializamos los pesos de la Capa 1
w = np.random.random(500)
w11 = w[:100]
w12 = w[100:200]
w13 = w[200:300]
w14 = w[300:400]
w15 = w[400:500]
W1=[w11,w12,w13,w14,w15]
#Inicializamos los pesos anteriores
w = np.zeros(500)
w11ant = w[:100]
w12ant = w[100:200]
w13ant = w[200:300]
w14ant = w[300:400]
w15ant = w[400:500]
W1ant = [w11ant,w12ant,w13ant,w14ant,w15ant]

#Inicializamos los pesos de la Capa 2
w = np.random.random(25)
w21 = w[:5]
w22 = w[5:10]
w23 = w[10:15]
w24 = w[15:20]
w25 = w[20:25]
W2 = [w21,w22,w23,w24,w25] 
#Inicializamos los pesos anteriores
w = np.zeros(25)
w21ant = w[:5]
w22ant = w[5:10]
w23ant = w[10:15]
w24ant = w[15:20]
w25ant = w[20:25]
W2ant = [w21ant,w22ant,w23ant,w24ant,w25ant]

#Incializamos los pesos de la Capa 3
w = np.random.random(15)
w31 = w[:5]
w32 = w[5:10]
w33 = w[10:15]
W3 = [w31,w32,w33]
#Inicializamos los pesos anteriores
w = np.zeros(15)
w31ant = w[:5]
w32ant = w[5:10]
w33ant = w[10:15]
W3ant = [w31ant,w32ant,w33ant]
#Conversiones
W1ant = np.array(W1ant)
W2ant = np.array(W2ant)
W3ant = np.array(W3ant)

Want = [W1ant,W2ant,W3ant]
#Bias
b = random.random()

#Factor de aprendizaje
alfa = np.array(random.random())
beta = np.array(random.random())

#Codificacion de clases
#b = 100
#d = 010
#f = 001

In [3]:
data = (pd.read_csv(os.path.join(os.path.abspath(''),"data","distorsionadas",'100','letras.csv'),sep=';',header=None)).to_numpy()
#Convertimos el dataframe en array numpy
data_train = data[:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8)+1:int(len(data)*0.8)+int(len(data)*0.15)]
data_validation = data[int(len(data)*0.8)+int(len(data)*0.15)+1:99]

In [4]:
#Dividiendo data train en una tupla (entrada,clase)
letras_train = []
for letra in data_train:
    x_test = letra[:100]
    y_test = letra[100:]
    letras_train.append((x_test, y_test))


In [6]:

for i in range(1):

    #Primer capa
    ys1 =[]
    for j in range(len(W1)):
        #Suma ponderada
        Z = np.dot(letras_train[i][0],W1[j])
        #Funcion de activacion
        ys1.append(lineal(Z+b))
    #print("Primer capa: ", ys1)

    #Segunda capa
    ys2 = []
    for j in range(len(W2)):
        #Suma ponderada
        Z = np.dot(ys1,W2[j])
        #Funcion de activacion
        ys2.append(lineal(Z+b))
    #print("2da capa: ", ys2)
    #Capa de salida
    ys3 = []
    for j in range(len(W3)):
        #Suma ponderada
        Z = np.dot(ys2,W3[j])
        #Funcion de activacion
        ys3.append(sigmoide(Z+b))
    #print("Capa salida: ", ys3)

    #!!-------Backpropagation-----!!
    ys1 = np.array(ys1)
    ys2 = np.array(ys2)
    ys3 = np.array(ys3)
    activations = [ys1,ys2,ys3]
    W1 = np.array(W1)
    W2 = np.array(W2)
    W3 = np.array(W3)
    W = [W1,W2,W3]
    ye = letras_train[i][1]
    deltas = Backpropagation(ye,activations,W[1:])
    #!!----- Gradient descent------!!
    Gradientdescent(deltas,W,Want,alfa,beta)

[[0.0011775919258926147, 0.0036595827108167056, 0.0036712627592272364, 0.0022181542979040104, 0.002635572634348126], [0.010416335948757014, 0.012515403756943677, 0.0064260361503422295, 0.008333613425572811, 0.012538823329340316], array([ 0.10160899, -0.01538954,  0.10503288])]


In [16]:
"""Backpropagationi=0
for w, want in zip(reversed(W),reversed(Want)):
    new_weight = []
    wl = np.transpose(w)
    wlant = np.transpose(want)
    for j in range(len(wl)):
      new_weight.append(wl[j]+deltas[i]*alfa+beta*(wl[j]-wlant[j]))
    i=i+1
new_weight"""

[array([0.36516633, 0.63549374, 1.16795829, 1.00049764, 0.09447925]),
 array([0.10916439, 0.94919452, 0.22054502, 0.98592568, 0.25393599]),
 array([0.82727268, 0.91659897, 0.76375873, 0.58170985, 0.53615217]),
 array([0.46002078, 0.83147233, 0.48304307, 0.35682587, 1.13020269]),
 array([0.12003955, 0.03872579, 0.99159087, 0.98965693, 0.64056366]),
 array([1.19008549, 0.77620029, 1.18766896, 0.05517096, 0.56825011]),
 array([0.60766007, 1.14123044, 0.36366737, 0.78015705, 0.41021166]),
 array([0.92986038, 0.43316829, 0.64906011, 1.01642684, 0.49069279]),
 array([0.25425249, 0.01015763, 0.28400121, 0.71304099, 0.19192506]),
 array([0.05405666, 1.12797241, 0.89377646, 0.52060697, 0.33574268]),
 array([0.69676366, 0.10538738, 0.53854305, 0.56963629, 0.93027347]),
 array([0.5662262 , 0.86385079, 1.16246416, 0.63552546, 1.16667422]),
 array([0.73631199, 0.49000451, 0.91497582, 0.98189431, 0.98436029]),
 array([0.01546228, 0.88864037, 1.04943304, 0.14865585, 1.10732197]),
 array([0.66074258, 

In [8]:
Want= W
Want[2]

array([[0.44377569, 0.48960061, 0.13207541, 0.53939096, 0.29925981],
       [0.21933377, 0.98718359, 0.45049866, 0.66910677, 0.11044363],
       [0.0798646 , 0.3721311 , 0.51739308, 0.02894144, 0.47833275]])

In [16]:
rev = deltas[::-1]
rev  

[[0.0009083471042714072,
  0.0015124723586379862,
  0.0005652500851094652,
  0.0014316443554611086,
  0.001466869623139155],
 [0.005850471229177693,
  0.004537502860842298,
  0.005771971501543688,
  0.0028675297553976582,
  0.010394887243390603],
 array([ 0.14576607, -0.0809144 ,  0.14480177])]