In [3]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from function import lineal, sigmoide, derivate_sigmoide, derivate_lineal
import os
import math

In [5]:
#Inicializamos los pesos de la Capa 1
w = np.random.random(500)
w11 = w[:100]
w12 = w[100:200]
w13 = w[200:300]
w14 = w[300:400]
w15 = w[400:500]
W1=[w11,w12,w13,w14,w15]

#Inicializamos los pesos de la Capa 2
w = np.random.random(25)
w21 = w[:5]
w22 = w[5:10]
w23 = w[10:15]
w24 = w[15:20]
w25 = w[20:25]
W2 = [w21,w22,w23,w24,w25] 

#Incializamos los pesos de la Capa 3
w = np.random.random(15)
w31 = w[:5]
w32 = w[5:10]
w33 = w[10:15]
W3 = [w31,w32,w33]

#Bias
b = random.random()

#Factor de aprendizaje
alfa = random.random()

#Codificacion de clases
#b = 100
#d = 010
#f = 001

In [6]:
data = (pd.read_csv(os.path.join(os.path.abspath(''),"data","distorsionadas",'100','letras.csv'),sep=';',header=None)).to_numpy()
#Convertimos el dataframe en array numpy
data_train = data[:int(len(data)*0.8)]
data_test = data[int(len(data)*0.8)+1:int(len(data)*0.8)+int(len(data)*0.15)]
data_validation = data[int(len(data)*0.8)+int(len(data)*0.15)+1:99]

In [7]:
#Dividiendo data train en una tupla (entrada,clase)
letras_train = []
for letra in data_train:
    x_test = letra[:100]
    y_test = letra[100:]
    letras_train.append((x_test, y_test))


In [31]:
print("W3 sin actualizar:\n",W3)
print("W2 sin actualizar:\n",W2)
#print("W1 sin actualizar:\n",W1)

for i in range(80):

    #Primer capa
    ys1 =[]
    for j in range(len(W1)):
        #Suma ponderada
        Z = np.dot(letras_train[i][0],W1[j])
        #Funcion de activacion
        ys1.append(lineal(Z+b))
    #print("Primer capa: ", ys1)

    #Segunda capa
    ys2 = []
    for j in range(len(W2)):
        #Suma ponderada
        Z = np.dot(ys1,W2[j])
        #Funcion de activacion
        ys2.append(sigmoide(Z+b))
    #print("2da capa: ", ys2)
    #Capa de salida
    ys3 = []
    for j in range(len(W3)):
        #Suma ponderada
        Z = np.dot(ys2,W3[j])
        #Funcion de activacion
        ys3.append(sigmoide(Z+b))
    #print("Capa salida: ", ys3)
#!!-------Backpropagation-----!!
""" ys1 = np.array(ys1)
    ys2 = np.array(ys2)
    ys3 = np.array(ys3)
    #Delta en capa 3
    delta3 = []
    for j in range(len(ys3)):
        # error[j]*f'(a[j])
        derivate_cost =-error(letras_train[i][1][j], ys3[j])
        delta3.append(derivate_cost*derivate_sigmoide(ys3[j]))
    
    #Delta en capa 2
    delta2 = []
    W = np.transpose(W3)
    for j in range(len(W)):
        delta2.append(np.dot(W[j],delta3)*ys2[j])
   
    #Delta en capa oculta 1
    delta1 = []
    W = np.transpose(W2)
    for j in range(len(W)):
        delta1.append(np.dot(W[j],delta2)*ys1[j])
   
    
    #!!---- Gradient descent -------!!
    delta3 = np.array(delta3)
    delta2 = np.array(delta2)
    delta1 = np.array(delta1)
    W3 = np.transpose(W3)
    W2 = np.transpose(W2)
    W1 = np.transpose(W1)
    #Capa 3
    new_weight = []
    for j in range(len(W3)):
        new_weight.append(W3[j]+alfa*delta3*ys3)
    W3 = np.array(new_weight)
    
    #Capa 2
    new_weight = []
    for j in range(len(W2)):
        new_weight.append(W2[j]+alfa*delta2*ys2)
    W2 = np.array(new_weight)

    #Capa 1
    new_weight = []
    for j in range(len(W1)):
        new_weight.append(W1[j]+alfa*delta1*ys1)
    W1 = np.array(new_weight)
    #pesos actualizados
    W3 = np.transpose(W3)
    W2 = np.transpose(W2)
    W1 = np.transpose(W1)

print("W3 actualizado:\n",W3)
print("W2 actualizado:\n",W2)
#print("W1 actualizado:\n",W1)"""

W3 sin actualizar:
 [array([0.4793058 , 0.58889612, 0.10862043, 0.70112781, 0.51284263]), array([0.14094763, 0.40475785, 0.3895572 , 0.80724734, 0.92472162]), array([0.3217584 , 0.48529851, 0.0234447 , 0.81720372, 0.42295548])]
W2 sin actualizar:
 [array([0.60476186, 0.27042017, 0.90670334, 0.05598739, 0.73045147]), array([0.54855931, 0.67017803, 0.98204174, 0.62662338, 0.08892522]), array([0.80136586, 0.3940794 , 0.73128263, 0.58816777, 0.96487598]), array([0.69725818, 0.417247  , 0.19523209, 0.2187928 , 0.57715465]), array([0.40128621, 0.0986634 , 0.7530048 , 0.76516324, 0.33912259])]


' ys1 = np.array(ys1)\n    ys2 = np.array(ys2)\n    ys3 = np.array(ys3)\n    #Delta en capa 3\n    delta3 = []\n    for j in range(len(ys3)):\n        # error[j]*f\'(a[j])\n        derivate_cost =-error(letras_train[i][1][j], ys3[j])\n        delta3.append(derivate_cost*derivate_sigmoide(ys3[j]))\n    \n    #Delta en capa 2\n    delta2 = []\n    W = np.transpose(W3)\n    for j in range(len(W)):\n        delta2.append(np.dot(W[j],delta3)*ys2[j])\n   \n    #Delta en capa oculta 1\n    delta1 = []\n    W = np.transpose(W2)\n    for j in range(len(W)):\n        delta1.append(np.dot(W[j],delta2)*ys1[j])\n   \n    \n    #!!---- Gradient descent -------!!\n    delta3 = np.array(delta3)\n    delta2 = np.array(delta2)\n    delta1 = np.array(delta1)\n    W3 = np.transpose(W3)\n    W2 = np.transpose(W2)\n    W1 = np.transpose(W1)\n    #Capa 3\n    new_weight = []\n    for j in range(len(W3)):\n        new_weight.append(W3[j]+alfa*delta3*ys3)\n    W3 = np.array(new_weight)\n    \n    #Capa 2\n    

In [22]:
w = np.transpose(W3)
delta3 =[2,2,2]
delta3 =np.array(delta3)
print(w)
for i in range (len(w)):
    print(w[i]*delta3)


[[0.4793058  0.14094763 0.3217584 ]
 [0.58889612 0.40475785 0.48529851]
 [0.10862043 0.3895572  0.0234447 ]
 [0.70112781 0.80724734 0.81720372]
 [0.51284263 0.92472162 0.42295548]]
[0.95861161 0.28189526 0.64351681]
[1.17779224 0.80951571 0.97059702]
[0.21724085 0.7791144  0.0468894 ]
[1.40225562 1.61449468 1.63440745]
[1.02568525 1.84944324 0.84591095]


In [26]:
W =[W1,W2,W3]
delta3 = [2,2,2]
delta3 =np.array(delta3)

for capa in reversed(W):
    w = np.transpose(capa)
    for i in range(len(w)):
        print(w[i]*delta3)

[0.95861161 0.28189526 0.64351681]
[1.17779224 0.80951571 0.97059702]
[0.21724085 0.7791144  0.0468894 ]
[1.40225562 1.61449468 1.63440745]
[1.02568525 1.84944324 0.84591095]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 